AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  Database:
    Default: postgres
    Type: String
  DbHost:
    Default: docker.for.mac.localhost # because sam local runs in a docker container
    Type: String
  DbUser:
    Type: String
  DbPwd:
    Type: String
    NoEcho: true
Resources:
  ApiGateway:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: dev
  MessageLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      Timeout: 10
      Environment:
        Variables:
          PGHOST: !Ref DbHost
          PGUSER: !Ref DbUser
          PGDATABASE: !Ref Database
          PGPASSWORD: !Ref DbPwd
      Events:
        ProcessMessage:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /DSTU2/$process-message
            Method: post
  ConformanceLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: conformance/index.handler
      Runtime: nodejs10.x
      Events:
        GetConformance:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /metadata
            Method: get
  SmartConfigurationLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: bulkdata/index.handler
      Runtime: nodejs10.x
      Events:
        GetSmartConfiguration:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /.well-known/smart-configuration
            Method: get
