REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE ROLE developer;

GRANT CONNECT ON DATABASE dev TO developer;
GRANT USAGE, CREATE ON SCHEMA public TO developer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO developer;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO developer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO developer;

CREATE USER kmahalingam WITH ENCRYPTED PASSWORD 'dylan';
CREATE USER lli WITH ENCRYPTED PASSWORD 'kathy';

GRANT developer TO kmahalingam;
GRANT developer TO lli;